# Generated by Django 3.2.12 on 2022-04-01 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=40)),
                ('title', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
                ('user_pk', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
