# Generated by Django 3.2.12 on 2022-04-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouptrip', '0006_alter_message_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
